version: '3.9'
services:
  db-master:
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    image: mysql:debian
    container_name: db-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pbbs1959
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3008:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - db-network

  db-slave1:
    image: mysql:debian
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row --relay-log=mysql-relay-log --log-slave-updates=1
    container_name: db-slave1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pbbs1959
      MYSQL_MASTER_HOST: db-master
      MYSQL_MASTER_USER: root
      MYSQL_MASTER_PASSWORD: pbbs1959
      MYSQL_MASTER_PORT: 3306
    ports:
      - 3009:3306
    volumes:
      - ./data-slave1:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    depends_on:
      - db-master
    networks:
      - db-network

  db-slave2:
    image: mysql:debian
    command: --server-id=3 --log-bin=mysql-bin --binlog-format=row --relay-log=mysql-relay-log --log-slave-updates=1
    container_name: db-slave2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pbbs1959
      MYSQL_MASTER_HOST: db-master
      MYSQL_MASTER_USER: root
      MYSQL_MASTER_PASSWORD: pbbs1959
      MYSQL_MASTER_PORT: 3306
    ports:
      - 3010:3306
    volumes:
      - ./data-slave2:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    depends_on:
      - db-master
    networks:
      - db-network

networks:
      db-network:
